# Generated by Django 3.1.2 on 2020-10-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('hair_color', models.CharField(max_length=30)),
                ('skin_color', models.CharField(max_length=30)),
                ('eye_color', models.CharField(max_length=30)),
                ('birth_year', models.CharField(max_length=11)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('average_rating', models.FloatField(null=True)),
                ('max_rating', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homeworld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('known_residents_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='character.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.homeworld'),
        ),
        migrations.AddField(
            model_name='character',
            name='species_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.species'),
        ),
    ]
