# Generated by Django 3.1.2 on 2020-10-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_rating_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('character', models.IntegerField(primary_key=True, serialize=False)),
                ('rating_data', models.JSONField(default={'rates_sum': 0, 'times_rated': 0})),
                ('average_rating', models.FloatField(null=True)),
                ('max_rating', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='homeworld',
        ),
        migrations.RemoveField(
            model_name='character',
            name='species_name',
        ),
        migrations.DeleteModel(
            name='Homeworld',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.AlterField(
            model_name='rating',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.characterstats'),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
