# Generated by Django 3.1.2 on 2020-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20201014_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterstats',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='characterstats',
            name='rating_data',
        ),
        migrations.AddField(
            model_name='characterstats',
            name='rating_sum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='characterstats',
            name='times_rated',
            field=models.IntegerField(null=True),
        ),
    ]
