# Generated by Django 3.1.2 on 2020-10-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20201014_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterstats',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='characterstats',
            name='max_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='characterstats',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
